(dp0
S'/Users/johntordoff/osf.io/node_modules/share/webclient/text.js'
p1
S'Mea Blamea'
p2
sS'/Users/johntordoff/osf.io/node_modules/bower/node_modules/inquirer/node_modules/rx/src/core/linq/observable/_observabletimertimespanandperiod.js'
p3
g2
sS'/Users/johntordoff/osf.io/node_modules/bower/node_modules/inquirer/node_modules/cli-color/node_modules/es5-ext/math/cbrt/is-implemented.js'
p4
g2
sS'/Users/johntordoff/osf.io/node_modules/bower/node_modules/inquirer/node_modules/cli-color/node_modules/es5-ext/reg-exp/#/split/index.js'
p5
g2
sS'/Users/johntordoff/osf.io/website/static/vendor/bower_components/jquery-ui/ui/i18n/jquery.ui.datepicker-sv.js'
p6
g2
sS'/Users/johntordoff/osf.io/node_modules/mocha/node_modules/glob/test/mark.js'
p7
g2
sS'/Users/johntordoff/osf.io/node_modules/bower/node_modules/inquirer/node_modules/cli-color/node_modules/es5-ext/test/math/asinh/implement.js'
p8
g2
sS'/Users/johntordoff/osf.io/node_modules/babel-core/node_modules/bluebird/js/main/debuggability.js'
p9
g2
sS'/Users/johntordoff/osf.io/node_modules/babel-core/node_modules/core-js/library/fn/string/raw.js'
p10
g2
sS'/Users/johntordoff/osf.io/node_modules/share/node_modules/express/node_modules/connect/node_modules/serve-index/index.js'
p11
g2
sS'/Users/johntordoff/osf.io/node_modules/font-awesome-webpack/node_modules/less/test/browser/runner-legacy-spec.js'
p12
g2
sS'/Users/johntordoff/osf.io/node_modules/historyjs/node_modules/buildr/node_modules/cson/node_modules/cson-parser/node_modules/coffee-script/lib/coffee-script/browser.js'
p13
g2
sS'/Users/johntordoff/osf.io/node_modules/font-awesome-webpack/node_modules/less/lib/less/tree/ruleset.js'
p14
g2
sS'/Users/johntordoff/osf.io/node_modules/bower/node_modules/inquirer/node_modules/cli-color/node_modules/es5-ext/date/index.js'
p15
g2
sS'/Users/johntordoff/osf.io/website/static/vendor/bower_components/MathJax/unpacked/jax/output/HTML-CSS/fonts/TeX/AMS/Regular/Arrows.js'
p16
g2
sS'/Users/johntordoff/osf.io/node_modules/karma-webpack/node_modules/lodash/object/assign.js'
p17
g2
sS'/Users/johntordoff/osf.io/node_modules/babel-core/node_modules/core-js/fn/object/classof.js'
p18
g2
sS'/Users/johntordoff/osf.io/website/static/vendor/bower_components/MathJax/jax/output/HTML-CSS/fonts/STIX/General/Bold/PhoneticExtensions.js'
p19
g2
sS'/Users/johntordoff/osf.io/website/static/js/tests/forgotPassword.test.js'
p20
(lp21
(lp22
